version: '3'
services:
  backend:
    build: ./backend
    expose:
      - "4041"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:4041/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    build: ./frontend
    expose:
      - "4040"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://frontend:4040/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        max_attempts: 3

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
networks:
  default:
    driver: bridge
    name: TaskManagementSystem